var n=2.5145;
var result=Math.floor(n);
var result1=Math.ceil(n);
var result2=Math.round(n);
var randomNum=Math.random(n)*6;
var output=Math.round(randomNum);
console.log(result);
console.log(result1);
console.log(result2);
console.log(randomNum);
console.log(output);
